### ISSUE TITLE
Translate Process Failed

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/translate#14]
Hi,
After installing Translate and downloading models, I get this error when trying a translation with a source langage selected:

```
[translate] Avertissement: node:internal/modules/cjs/loader:1243
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/translate/node_modules/onnxruntime-node/bin/napi-v3/linux/x64//libonnxruntime.so.1.13.1)
    at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/config/www/nextcloud/apps/translate/node_modules/onnxruntime-node/dist/binding.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.12.1


POST /ocs/v2.php/translation/translate
from ****** by ***** at 2023-06-06T****
```

When not selecting a source langage, I get this different error:

```
[translate] Avertissement: /config/www/nextcloud/apps/translate/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
        ^

Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=musl node=18.12.1
    loaded from: /config/www/nextcloud/apps/translate/node_modules/cldpre

    at load.resolve.load.path (/config/www/nextcloud/apps/translate/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/config/www/nextcloud/apps/translate/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/config/www/nextcloud/apps/translate/node_modules/cldpre/index.js:2:39)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)

Node.js v18.12.1


POST /ocs/v2.php/translation/translate
from ****** by ***** at 2023-06-06T****
```

Looks like something is missing?

NC: v26.0.2
Translate: v1.1.3

**Comment by marcelklehr** [comment]
> libc=musl

This app requires GNU libc, musl is not supported

**Comment by louim-lbs** [comment]
I installed Nextcloud via the Docker image from Linuxserver. Does it mean that their image is the problem or is it related to my Synology NAS?

**Comment by marcelklehr** [comment]
the Docker image from Linuxserver is the problem, it's using Alpine Linux
