### ISSUE TITLE
Document size of models once downloaded

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/translate#26]
When `occ translate:download-models` it downloads around 9GB

```
# du -h -d1 /var/www/nextcloud/apps/translate/models
553M    /var/www/nextcloud/apps/translate/models/en-es
553M    /var/www/nextcloud/apps/translate/models/zh-de
611M    /var/www/nextcloud/apps/translate/models/fr-es
521M    /var/www/nextcloud/apps/translate/models/en-fr
535M    /var/www/nextcloud/apps/translate/models/de-zh
531M    /var/www/nextcloud/apps/translate/models/es-de
521M    /var/www/nextcloud/apps/translate/models/fr-en
611M    /var/www/nextcloud/apps/translate/models/es-fr
553M    /var/www/nextcloud/apps/translate/models/es-en
531M    /var/www/nextcloud/apps/translate/models/fr-de
531M    /var/www/nextcloud/apps/translate/models/de-es
513M    /var/www/nextcloud/apps/translate/models/en-de
553M    /var/www/nextcloud/apps/translate/models/en-zh
513M    /var/www/nextcloud/apps/translate/models/de-en
531M    /var/www/nextcloud/apps/translate/models/de-fr
553M    /var/www/nextcloud/apps/translate/models/zh-en
8.6G    /var/www/nextcloud/apps/translate/models
```

This is large enough to be worth mentioning it in the documentation. This is somewhat related with https://github.com/nextcloud/translate/issues/5. I wouldn't expect a precise size, but a note or a warning of the maximum size that I'd occupy if I were to download all the models, that is without specifying the `langs` parameter.

As a side note `occ translate:` seems to be an alias of   `occ translate:download-models`, is this wanted?

**Comment by marcelklehr** [comment]
> This is large enough to be worth mentioning it in the documentation. 

Good idea :) Done.

> As a side note occ translate: seems to be an alias of occ translate:download-models, is this wanted?

How did you come to that conclusion?

**Comment by pmarini-nc** [comment]
> How did you come to that conclusion?

Just tried it. I usually run occ app-scoped commands, with or without the colon, to evoke the help, but in this case it triggers the download. Maybe because there are no other commands?

**Comment by marcelklehr** [comment]
Are you sure it triggers the download?

**Comment by marcelklehr** [comment]
`occ translate` should just be a translation cli for testing purposes

**Comment by pmarini-nc** [comment]
```
# occ app:list | grep translate
  - translate: 1.1.6

# occ translate:
Downloading model de-en
Successful
Downloading model de-es
Successful
Downloading model de-fr
Successful
Downloading model de-zh
Successful
Downloading model en-de
Successful
Downloading model en-es
Successful
Downloading model en-fr
Successful
Downloading model en-zh
Successful
Downloading model es-de
Successful
Downloading model es-en
Successful
Downloading model es-fr
Successful
Downloading model es-zh
Model is not available, skipping
Downloading model fr-de
Successful
Downloading model fr-en
Successful
Downloading model fr-es
Successful
Downloading model fr-zh
Model is not available, skipping
Downloading model zh-de
Successful
Downloading model zh-en
Successful
Downloading model zh-es
Model is not available, skipping
Downloading model zh-fr
Model is not available, skipping

# occ translate
An unhandled exception has been thrown:
TypeError: OCA\Translate\Service\TranslateService::seq2seq(): Argument #2 ($input) must be of type string, null given, called in /var/www/nextcloud/apps/translate/lib/Command/Translate.php on line 45 and defined in /var/www/nextcloud/apps/translate/lib/Service/TranslateService.php:34
Stack trace:
#0 /var/www/nextcloud/apps/translate/lib/Command/Translate.php(45): OCA\Translate\Service\TranslateService->seq2seq()
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Translate\Command\Translate->execute()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('...')

```

**Comment by pmarini-nc** [comment]
Already there, it throws an exception...

**Comment by marcelklehr** [comment]
I think the solution is 

occ translate is the command to use translation on the cli.
occ translate:download-models is the command to download the models
`occ translate` on its own fails because it needs arguments
occ translate: downloads the models, because the download-models command is the only known command that starts with translate:
